version: "3"
services:
    dbatools1:v0.3.0
      image: jpomfret7/dbatools1:v0.3.0
      volumes:
        - mydata:/var/opt/backups
        - shared:/shared
        # Update this to wherever you want VS Code to mount the folder of your project
        - ..:/workspace:cached
      ports:
        - "8801:1433"
      container_name: dbatools1
      hostname: dbatools1
      
    dbatools2:v0.3.0
      image: jpomfret7/dbatools2:v0.3.0
      volumes:
        - mydata:/var/opt/backups
        - shared:/shared
        # Update this to wherever you want VS Code to mount the folder of your project
        # So that the second container is rebuilt everytime as well 
        - ..:/somewhereweirdworkspace:cached
      ports:
        - "8802:1433"
      container_name: dbatools2
      hostname: dbatools2


volumes:
  mydata:
  shared: